### PR TITLE
Allow user to create experiment in db after creating experiment rule set

### PR DESCRIPTION
**Pull request by drikusroor**
Per a suggestion by @hhoning 

This pull request adds a new feature that allows the user to create an experiment in the database after creating an experiment rule set, which you often want to do anyway.

## Screenshot

image

### CODE REVIEW

**Comment by BeritJanssen** [comment]
Good idea! Again, I would've liked an issue first to discuss with the team. Note that if you do this, the experiment still won't run because we cannot auto-attach a playlist, too.

**Comment by drikusroor** [comment]
> Good idea! Again, I would've liked an issue first to discuss with the team. Note that if you do this, the experiment still won't run because we cannot auto-attach a playlist, too.

I could expand it with a warning to the user that it still has to create and attach a playlist, or I could also ask the user if the script should automatically create an (empty) playlist. What do you think?

**Comment by BeritJanssen** [comment]
I'm not sure about the added value of this tbh. Let's discuss this in the next Scrum meeting.

**Comment by hhoning** [comment]
My original suggestion came from the idea that CreateExperiment, with a certain nam, should show up with that name in the Experiment tab in the Admin (since you just generated that). But it does not. It in fact ends up a level lower in the Ruleset menu, doesn't it? So rename CreateExperiment into CreateRuleset would solve it :-)

**Comment by BeritJanssen** [comment]
Should we close this branch, and instead rename the command to `create_ruleset`? I think we *do* want users to jump through the hoops of going into the admin interface & setting up a playlist as well. *Or* we check in a mini playlist into this repo, which will be auto-loaded and linked as well. But I do worry that if you "automagically" set everything up, the threshold to using the admin interface is going to actually get higher.

**Pull request closed without merging**
