### PR TITLE
Added: Add upload and export functionality to PlaylistAdmin

### LINKED ISSUE #591: Upload / download playlist csvs
Instead of copying / pasting csv files, it may be interesting to add buttons to upload / download .csv files to / from the database.

### PR DESCRIPTION
**Pull request by drikusroor**
This pull request adds the ability to upload CSV files and export playlists to CSV and JSON formats in the PlaylistAdmin section.

Resolves #591

### CODE REVIEW

**Review by BeritJanssen — CHANGES_REQUESTED** [review]
Nice! I tested it and noticed the following:
- the csv export has two leading columns and an extra column after the filename, e.g.:
2020,2020,default,1_tempo,0.0,15.856326530612245,BAT/1_tempo.wav,[],0,0,0

This means the file cannot be uploaded / pasted into the csv field again.

It would also be nice to have the download button closer to the text field. Next to it perhaps? Or directly below?
Screenshot 2024-01-16 at 17 47 08

It's probably better to get rid of the JSON export here - I don't think it would be used by anyone. The desired functionality is to be able to import and export playlist csvs.

**Comment by drikusroor** [comment]
> Nice! I tested it and noticed the following:
> 
> * the csv export has two leading columns and an extra column after the filename, e.g.:
>   2020,2020,default,1_tempo,0.0,15.856326530612245,BAT/1_tempo.wav,[],0,0,0
> 
> This means the file cannot be uploaded / pasted into the csv field again.

The first two columns are the ids and the pks. They can probably be removed I think? The other field used to be the play count. However, in the original input description (when importing csv data) it speaks about `restricted_to_nl`, which is a field that doesn't exist anymore. When I look at the Section model, I see the fields `play_count` and `code` after the `filename`. Which one should be exported?

> It would also be nice to have the download button closer to the text field. Next to it perhaps? Or directly below? Screenshot 2024-01-16 at 17 47 08

I tried to do this and found it quite tedious. Do you know an easy way to inject that button there? 🤔 

> It's probably better to get rid of the JSON export here - I don't think it would be used by anyone. The desired functionality is to be able to import and export playlist csvs.

👍 Removed it

**Comment by BeritJanssen** [comment]
Ah, looks like we also need to update the import from csv. No, we don't want to export section ids here, but export exactly the same format csv that the admin interface expects in the TextField (see the small helper text under the TextField in the screenshot). I wasn't aware that `restricted_to_nl` was removed. The last columns (according to the help line under the csv input field) should be "restricted_to_nl", "tag" and "group". We should then also check the `process_csv` function again.

I think we might indeed need to write a custom html form in order to achieve the move of the button, now that I think of it. 🤔 The button is visible enough where it is, so it's probably not worth it.

**Comment by BeritJanssen** [comment]
I still went after what happened to the `restrict_to_nl` field on `Session`. It is actually still there, but now as a field of `Song`, as a `JSONField`, with the reasoning we could add in lists of country codes in which playback was *allowed*. @jaburgoyne actually indicated that we don't need this restriction at all anymore, so I'll file an issue to remove `Song.restricted`, which will have consequences both on this feature, and on `playlist.update_sections`.

**Pull request merged**
