### PR TITLE
Chore: Merge main into develop (after 0.8.0)

### PR DESCRIPTION
**Pull request by drikusroor**

### CODE REVIEW

**Comment by BeritJanssen** [comment]
I was confused at first why this would be necessary. In git-flow, hotfix branches are always merged to develop *and* main, so then you'd never merge main into develop.

**Review by BeritJanssen — COMMENTED** [review]
I'm confused. I see commits in this branch which aren't reflected in the "files changed" - could it be the hotfix commits have already be integrated in develop?

**Comment by drikusroor** [comment]
Yes, this PR is probably not necessary. I made a hotfix last friday but I haven't properly used git-flow like we should

**Comment by BeritJanssen** [comment]
We should still increase the version number on develop though, and the template update for a bug report has also not been picked up in develop yet. So I don't think this is completely superfluous.

**Pull request closed without merging**
